version: '3'

services:
  match-manager:
    image: match-manager
    ports:
      - "8080:8080"
    build: .
    environment:
      - PORT=8080
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=match_manager
      - POSTGRES_USER=crm_user
      - POSTGRES_PASSWORD=crm_pass
    volumes:
      - C://logs:/home/match-manager/logs

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: match_manager
      POSTGRES_USER: crm_user
      POSTGRES_PASSWORD: crm_pass

