CREATE TABLE match
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description TEXT NOT NULL,
    match_date  DATE,
    match_time  TIME,
    team_a      TEXT NOT NULL,
    team_b      TEXT NOT NULL,
    sport       INT  NOT NULL
);

CREATE TABLE match_odds
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id  BIGINT  NOT NULL,
    specifier TEXT    NOT NULL,
    odd       DECIMAL(2,1) NOT NULL,

    FOREIGN KEY (match_id) REFERENCES match (id)
);